# Generated by Django 5.2.12 on 2026-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_hotspot', '0002_crimereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='time',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
