# Generated by Django 5.2.12 on 2026-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_hotspot', '0003_remove_crimereport_date_remove_crimereport_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
